apiVersion: v1
kind: Pod
metadata:
  name: portal-news
  labels: 
    app: portal-news
spec:
  containers:
    - name: portal-news-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80