apiVersion: v1
kind: Pod
metadata:
  name: system-news
  labels: system-news
spec:
  containers:
    name: system-news-container
    image: aluracursos/sistema-noticias:1
    port:
      - containerPort: 80
