apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-news-replicaset
spec:
  template:
    metadata:
      name: 
      labels:
        app: portal-news
    spec:
      containers:
        - name: portal-news-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: portal-news